### ISSUE TITLE
npm i --save react-native-3d-swiper is not working

### ISSUE THREAD

**Issue by yu629** [Bobby-hewitt/react-native-3d-swiper#1]

**Comment by bobby-hewitt** [comment]
I just tried it and it seems to be working fine.  Try npm install --save instead?

**Comment by bobby-hewitt** [comment]
I'm going to close this as I haven't heard back and no one else has experienced the problem

**Comment by bobby-hewitt** [comment]
I'm going to close this as I haven't heard back and no one else has experienced the problem
